set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR mipsel)
set(CMAKE_C_COMPILER /usr/local/bin/mipsel-linux-muslsf-gcc)
set(CMAKE_CXX_COMPILER /usr/local/bin/mipsel-linux-muslsf-g++)
set(CMAKE_AR /usr/local/bin/mipsel-linux-muslsf-ar)
set(CMAKE_RANLIB /usr/local/bin/mipsel-linux-muslsf-ranlib)
set(CMAKE_C_FLAGS_INIT "-fPIC")
set(CMAKE_CXX_FLAGS_INIT "-fPIC")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-static -Wl,-Bstatic -latomic")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
